                                                  Transcendental functions

In [2]:
import numpy as np

x=np.array([2,4,1,6,3,9,66,32,12])


In [4]:
print(x)

[ 2  4  1  6  3  9 66 32 12]


In [5]:
#ARGMAX                >>  "Argmax returns the index of the maximum value in an array "
np.argmax(x)

6

In [6]:
#ARGMIN                >>  "Argmin returns the index of the minimum value in an array "
np.argmin(x)

2

In [7]:
#MEDIAN                >> "function that calculates the median of an array"
np.median(x)

6.0

In [8]:
#MEAN                >> "function that calculates the mean of an array"
np.mean(x)

15.0

In [10]:
#STANDARD DEVIATION    >> "Function that calculates spread or devation"
np.std(x)

20.127372185934036

In [13]:
#PERCENTILE          >> "Calculates Percentile  with given percentage value "
np.percentile(x,75)

12.0

In [17]:
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
#AXIS ADDITION         >> "Horizontal axis addition"
np.sum(z,axis=1)

array([10, 26, 42])

In [23]:
#AXIS ADDITION         >> "Vertical axis addition"
np.sum(z,axis=0)

array([15, 18, 21, 24])