                                            ARRAYS AND ARANGE FUNCTION

In [1]:
# Numpy arrays and arange function .

#  ARRAYS

import numpy as np

x=np.array([0,2,4,6,8,10])

print(x)



[ 0  2  4  6  8 10]


In [2]:
# Arange

z=np.arange(1,21)

print(z)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:

#Arange with Steps

z_1=np.arange(0,21,2)

print(z_1)

[ 0  2  4  6  8 10 12 14 16 18 20]
