                                                   FLATTENING

In [3]:
#CREATING 2x3 ARRAY

import numpy as np

a=np.array([[1,2,3],[4,5,6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
#RAVEL    >>  "Join array in single dimension"

x_1=np.ravel(a)

print(x_1)

[1 2 3 4 5 6]


In [6]:
#TRANSPOSE 

x_2=a.T


print(x_2)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
#RESHAPE

x_3=a.shape

x_4=a.reshape(3,2)

print(x_3)

print()

print(x_4)

(2, 3)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
#ALTERING EXISTING ARRAY
a_01=np.array([[1,2,3],[4,5,6]])

a_01[0,0]=9



In [39]:
print(a_01)

[[9 2 3]
 [4 5 6]]


In [47]:
#ARGSORT    >> "Sort's in asc order by index"

z=np.array([22,45,3,9,12,1,23])

print(z)

print()

np.argsort(z)

[22 45  3  9 12  1 23]



array([5, 2, 3, 4, 0, 6, 1], dtype=int64)

In [55]:
# RESIZE

y=np.arange(0,10)

y.resize(20,)

print(y)

[0 1 2 3 4 5 6 7 8 9 0 0 0 0 0 0 0 0 0 0]
