                                    LINSPACE, ONES, EYE, DIAGONAL ,ZEROES

In [1]:
import numpy as np

#LINSPACE

x=np.linspace(0,1,6)

print (x)


[0.  0.2 0.4 0.6 0.8 1. ]


In [5]:
#ONES

y=np.ones([3,3])

print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#Zeroes

z=np.zeros([2,3])

print(z)


[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#Eye

xx=np.eye(3,3)

print(xx)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#Diagonal

yy=np.diag([1,2,3,4])

print(yy)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
