                                                 BROADCASTING

In [3]:
#HOW TO CREATE 1-D ARRAY
import numpy as np

x=np.array([1,2,3])

print(x)

[1 2 3]


In [4]:
# HOW TO CREATE 2-D MATRIX

y=np.array([[1,2,3],[4,5,6]])

print(y)

[[1 2 3]
 [4 5 6]]


In [6]:
# HOW TO CREATE 3-D MATRIX

z=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#BROADCASTING

a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])

b=np.array([[1,2,3],[1,1,1],[2,2,2],[3,3,3]])

print(a+b)

#ELEMENT WISE ADDOTION

[[ 1  2  3]
 [11 11 11]
 [22 22 22]
 [33 33 33]]


In [15]:
# NOW 3X3 + 1X3

z=np.array([[1,2,3],[4,5,6],[7,8,9]])

x=np.array([1,2,3])

print("Z=",z)


print("X=",x)

print(z+x)     #i.e it'll replicate the remainning rows with given first row

Z= [[1 2 3]
 [4 5 6]
 [7 8 9]]
X= [1 2 3]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [21]:
#NOW 4X1 + 1X3

o=np.array([[0],[10],[20],[30]])

p=np.array([1,2,3])

print(o)
print(p)

print(o+p)     

[[ 0]
 [10]
 [20]
 [30]]
[1 2 3]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [23]:
#TILE F'n

data=np.tile(np.arange(0,100,20) ,(3,1))

print(data)

[[ 0 20 40 60 80]
 [ 0 20 40 60 80]
 [ 0 20 40 60 80]]


In [25]:
data1=np.tile(np.arange(0,100,20) ,(3,2))

print(data1)

[[ 0 20 40 60 80  0 20 40 60 80]
 [ 0 20 40 60 80  0 20 40 60 80]
 [ 0 20 40 60 80  0 20 40 60 80]]


In [26]:
#Shape
data=np.tile(np.arange(0,100,20) ,(3,1))
data.shape

(3, 5)