In [1]:
import numpy as np
#LINSPACE

x=np.linspace(0,1,6)
print (x)


[0.  0.2 0.4 0.6 0.8 1. ]


In [5]:

#ONES

y=np.ones([3,3])
print(y)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#Zeroes

z=np.zeros([2,3])
print(z)



[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:

#Eye

xx=np.eye(3,3)
print(xx)

#Diagonal

yy=np.diag([1,2,3,4])
print(yy)