In [4]:
#SUB ARRAYS
import numpy as np
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
#SCALAR ADDITION
a=np.array([2,4,6,8,10,12,14])
b=np.array([1,3,5,7,9,11,13])
print(a+b)

[ 3  7 11 15 19 23 27]


In [6]:
#SCALAR SUBTRACTION
a=np.array([2,4,6,8,10,12,14])
b=np.array([1,3,5,7,9,11,13])
print(a-b)

[1 1 1 1 1 1 1]


In [7]:
#SCALAR MULTIPLICATION
a=np.array([2,4,6,8,10,12,14])
b=np.array([1,3,5,7,9,11,13])
print(a*b)

[  2  12  30  56  90 132 182]


In [8]:
#SCALAR DIVISION
a=np.array([2,4,6,8,10,12,14])
b=np.array([1,3,5,7,9,11,13])
print(a*b)

[  2  12  30  56  90 132 182]
