                                                    Transcendental functions

In [12]:
import numpy as np
x=np.array([1,30,60,90,180])
print(x)

[  1  30  60  90 180]


In [13]:
# SIN f'n
np.sin(x)

array([ 0.84147098, -0.98803162, -0.30481062,  0.89399666, -0.80115264])

In [14]:
#LOG  f'n
np.log(x)

array([0.        , 3.40119738, 4.09434456, 4.49980967, 5.19295685])

In [15]:
# COS f'n
np.cos(x)

array([ 0.54030231,  0.15425145, -0.95241298, -0.44807362, -0.59846007])

In [16]:
#TAN f'n
np.tan(x)

array([ 1.55740772, -6.4053312 ,  0.32004039, -1.99520041,  1.33869021])

In [17]:
#EXP  F'n
np.exp(x)

array([2.71828183e+00, 1.06864746e+13, 1.14200739e+26, 1.22040329e+39,
       1.48938420e+78])

In [18]:
#SUM F'n
np.sum(x)

361

In [19]:
#MAX f'n
np.max(x)

180

In [23]:
#MIN f'n
np.min(x)

1